name: gnn-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - ipython
  - numpy
  - pandas
  - networkx
  - yapf
  - pip
  - pip:
      - torch-geometric
      - pip-tools

