train_file: "./data/metr_la/train_iti.npz"
test_file: "./data/metr_la/test_iti.npz"
val_file: "./data/metr_la/val_iti.npz"
forecast_horizon: 1
toy_data: False
lr: 0.015
weight_decay: 0.95
batch_size: 32
save_model: True
model_name: model_001
n_epochs: 20
pickled_files:  "metr_la/adj_mx_la.pkl"
model: "GCN"
gpu: True

# model parameters
"nhid": 100
"nclass": 1
"num_nodes": 207
"num_features": 2
"nhid_multipliers": [1, 2]
